# Generated by Django 4.2.26 on 2025-11-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
