# Generated by Django 4.0.10 on 2025-06-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0002_auditlog_cart_alter_auditlog_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
    ]
